CREATE TABLE IF NOT EXISTS users (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone            VARCHAR(255) UNIQUE,
    email            VARCHAR(255) UNIQUE,
    name             VARCHAR(255),
    password_hash    VARCHAR(255),
    created_at       TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_users_phone ON users (phone);
CREATE INDEX IF NOT EXISTS ix_users_email ON users (email);

CREATE TABLE IF NOT EXISTS cards (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          INTEGER REFERENCES users (id),
    bank_name        VARCHAR(255),
    card_name        VARCHAR(255),
    last4            VARCHAR(4),
    cashback_rules   JSONB,
    limit_monthly    DOUBLE PRECISION,
    created_at       TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_cards_id ON cards (id);

CREATE TABLE IF NOT EXISTS transactions (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          INTEGER REFERENCES users (id),
    card_id          INTEGER REFERENCES cards (id),
    amount           DOUBLE PRECISION,
    category         VARCHAR(255),
    cashback_earned  DOUBLE PRECISION,
    created_at       TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_transactions_id ON transactions (id);

CREATE TABLE IF NOT EXISTS recommendations (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER REFERENCES users (id),
    message     TEXT,
    type        VARCHAR(255),
    created_at  TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_recommendations_id ON recommendations (id);
